spring:
  datasource:
    url: jdbc:postgresql://8.134.198.180:8888/postgres?currentSchema=the_great_project&amp;
    username: guan  
    password: Chong@123
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 40MB        # file-size 总文件大小       MB 大写
      max-request-size: 40MB     # request-size 单个文件大小  MB 大写
      enabled: true 

server:
  port: 8080
  ssl:
    enabled: true
    #指定证书
    key-store: classpath:test.keystore
    #使用上面方法生成的格式为JKS
    key-store-type: JKS
    #默认为TLS，
    protocol: TLS
    #别名
    key-alias: test
    #私钥密码
    key-password: 123456
    #store文件密码
    key-store-password: 123456
  servlet:
    session:
      cookie:
        secure: true

mybatis:
  # 配置XML映射文件中指定的实体类别名路径
  type-aliases-package: com.spring.databaseApp.mapper
  # 配置MyBatis的xml配置文件路径
  mapper-locations: classpath:mapper/*.xml